const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  username: state => state.user.username,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  role: state => state.user.role,
  role_type_id: state => state.user.role_type_id,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,

  adviser: state => state.order.adviser,
  beautician: state => state.order.beautician,
  group: state => state.order.group,
  room: state => state.order.room,
  serviceList: state => state.order.serviceList,
  chargemixture_type: state => state.order.chargemixture_type,
  inventory_keeper: state => state.order.inventory_keeper,
  reception: state => state.order.reception,
  payment_type: state => state.order.payment_type,
  sys_role: state => state.order.sys_role,
  finance: state => state.order.finance,
  operate_order_status: state => state.order.operate_order_status,
  change_flow_status: state => state.order.change_flow_status,
}
export default getters
